/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CMIInventories {
  id: Generated<number>;
  inventories: Generated<string | null>;
  player_id: Generated<number | null>;
}

export interface CmiPlaytime {
  date: Generated<number | null>;
  h0: Generated<number | null>;
  h1: Generated<number | null>;
  h10: Generated<number | null>;
  h11: Generated<number | null>;
  h12: Generated<number | null>;
  h13: Generated<number | null>;
  h14: Generated<number | null>;
  h15: Generated<number | null>;
  h16: Generated<number | null>;
  h17: Generated<number | null>;
  h18: Generated<number | null>;
  h19: Generated<number | null>;
  h2: Generated<number | null>;
  h20: Generated<number | null>;
  h21: Generated<number | null>;
  h22: Generated<number | null>;
  h23: Generated<number | null>;
  h3: Generated<number | null>;
  h4: Generated<number | null>;
  h5: Generated<number | null>;
  h6: Generated<number | null>;
  h7: Generated<number | null>;
  h8: Generated<number | null>;
  h9: Generated<number | null>;
  id: Generated<number>;
  player_id: Generated<number | null>;
}

export interface CmiPlaytimereward {
  id: Generated<number>;
  onetime: Generated<string | null>;
  player_id: Generated<number | null>;
  repeatable: Generated<string | null>;
}

export interface CmiUsers {
  AFRecharge: Generated<string | null>;
  AlertReason: Generated<string | null>;
  AlertUntil: Generated<number | null>;
  Balance: Generated<number | null>;
  BannedAt: Generated<number | null>;
  BannedBy: Generated<string | null>;
  BannedUntil: Generated<number | null>;
  BanReason: Generated<string | null>;
  Charges: Generated<string | null>;
  ChatColor: Generated<string | null>;
  Collision: Generated<number | null>;
  Cooldowns: Generated<string | null>;
  Cuffed: Generated<number | null>;
  DeathLocation: Generated<string | null>;
  DisplayName: Generated<string | null>;
  Economy: Generated<string | null>;
  FakeAccount: Generated<number | null>;
  FlightCharge: Generated<number | null>;
  flightChargeEnabled: Generated<number | null>;
  Flying: Generated<number | null>;
  Glow: Generated<string | null>;
  Homes: Generated<string | null>;
  id: Generated<number>;
  Ignores: Generated<string | null>;
  Ips: Generated<string | null>;
  Jail: Generated<string | null>;
  JailedUntil: Generated<number | null>;
  JailReason: Generated<string | null>;
  JoinedCounter: Generated<number | null>;
  Kits: Generated<string | null>;
  LastLoginTime: Generated<number | null>;
  LastLogoffTime: Generated<number | null>;
  LockedIps: Generated<string | null>;
  LogOutLocation: Generated<string | null>;
  Mail: Generated<string | null>;
  Muted: Generated<string | null>;
  NameColor: Generated<string | null>;
  NamePrefix: Generated<string | null>;
  NameSuffix: Generated<string | null>;
  nickname: Generated<string | null>;
  Notes: Generated<string | null>;
  Options: Generated<string | null>;
  player_uuid: Generated<string | null>;
  PlaytimeOptimized: Generated<number | null>;
  pTime: Generated<number | null>;
  Rank: Generated<string | null>;
  Skin: Generated<string | null>;
  TeleportLocation: Generated<string | null>;
  tFly: Generated<number | null>;
  tGod: Generated<number | null>;
  TotalPlayTime: Generated<number | null>;
  UserMeta: Generated<string | null>;
  username: Generated<string | null>;
  Vanish: Generated<string | null>;
  Votifier: Generated<number | null>;
  Warnings: Generated<string | null>;
}

export interface DB {
  CMI_inventories: CMIInventories;
  cmi_playtime: CmiPlaytime;
  cmi_playtimereward: CmiPlaytimereward;
  cmi_users: CmiUsers;
}
