/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface LandsLands {
  area: string;
  balance: Generated<number>;
  category: Generated<string | null>;
  created_at: Date;
  icon: Generated<string | null>;
  inbox: Generated<string | null>;
  level: number;
  limits: Generated<string | null>;
  members: string;
  name: string;
  nation: Generated<string | null>;
  server: string;
  shield: Generated<number>;
  spawn: Generated<string | null>;
  stats: Generated<string | null>;
  storage: Generated<string | null>;
  title: Generated<string | null>;
  type: string;
  ulid: string;
  world: string;
}

export interface LandsLandsClaims {
  areas: Generated<string | null>;
  areas_amount: Generated<number | null>;
  blocks: Generated<string | null>;
  chunks: Generated<string | null>;
  chunks_amount: Generated<number | null>;
  land: string;
  world: string;
}

export interface LandsPlayers {
  chatmode: Generated<string | null>;
  edit_land: Generated<string | null>;
  flags: Generated<string | null>;
  invites: Generated<string | null>;
  limits: Generated<string | null>;
  name: string;
  uuid: string;
}

export interface LandsServers {
  flags: Generated<string | null>;
  last_seen: Date;
  server: string;
  timestamps: Generated<string | null>;
  version: string;
  version_prev: string;
}

export interface LandsWars {
  attacker: string;
  attacker_stats: string;
  defender: string;
  defender_stats: string;
  started_at: Date;
  tribute: Generated<number>;
}

export interface LandsWarsDeclarations {
  attacker: string;
  defender: string;
  mutual: Generated<Buffer>;
  preparation_time: Generated<number | null>;
  sent_at: Date;
  tribute: Generated<number>;
}

export interface LandsWorlds {
  flags_natural: Generated<string | null>;
  flags_role: Generated<string | null>;
  name: string;
  server: string;
  uid: string;
  ulid: string;
}

export interface DB {
  lands_lands: LandsLands;
  lands_lands_claims: LandsLandsClaims;
  lands_players: LandsPlayers;
  lands_servers: LandsServers;
  lands_wars: LandsWars;
  lands_wars_declarations: LandsWarsDeclarations;
  lands_worlds: LandsWorlds;
}
