/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AjparkourPlayers {
  gamesplayed: Generated<number | null>;
  id: string;
  material: Generated<string | null>;
  name: Generated<string | null>;
}

export interface AjparkourScores {
  area: Generated<string | null>;
  id: Generated<number>;
  player: Generated<string | null>;
  score: Generated<number | null>;
  time: Generated<number | null>;
}

export interface IjEnabledPlayers {
  isEnabled: Generated<string | null>;
  Item_Name: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjFirstCommands {
  Command_String: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjFirstJoin {
  Item_Name: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
}

export interface IjFirstWorld {
  Item_Name: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjIpLimits {
  IP_Address: Generated<string | null>;
  Item_Name: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjMapIds {
  Map_ID: Generated<string | null>;
  Map_IMG: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
}

export interface IjOnCooldown {
  Cooldown: Generated<string | null>;
  Duration: Generated<string | null>;
  Item_Name: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjReturnCraftitems {
  Inventory64: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
}

export interface IjReturnItems {
  Inventory64: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Region_Name: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface IjReturnSwitchItems {
  Inventory64: Generated<string | null>;
  Player_UUID: Generated<string | null>;
  Time_Stamp: Generated<string | null>;
  World_Name: Generated<string | null>;
}

export interface DB {
  ajparkour_players: AjparkourPlayers;
  ajparkour_scores: AjparkourScores;
  ij_enabled_players: IjEnabledPlayers;
  ij_first_commands: IjFirstCommands;
  ij_first_join: IjFirstJoin;
  ij_first_world: IjFirstWorld;
  ij_ip_limits: IjIpLimits;
  ij_map_ids: IjMapIds;
  ij_on_cooldown: IjOnCooldown;
  ij_return_craftitems: IjReturnCraftitems;
  ij_return_items: IjReturnItems;
  ij_return_switch_items: IjReturnSwitchItems;
}
