/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type PaymentFiatStatus = "Canceled" | "Pending" | "Succeeded" | "WaitingForCapture";

export type PaymentStatus = "cancelled" | "captured" | "created" | "failed" | "received";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Payments {
  captured: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  currency: string;
  hash: string;
  id: Generated<string>;
  lt: Int8;
  nickname: string;
  orderid: string;
  payment_type: string;
  payment_value: string;
  price: Int8;
  status: PaymentStatus;
  wallet: string | null;
}

export interface PaymentsFiat {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  nickname: string;
  orderid: string;
  payment_type: string;
  payment_value: string;
  price: Int8;
  status: PaymentFiatStatus;
}

export interface DB {
  payments: Payments;
  payments_fiat: PaymentsFiat;
}
