/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface PlayerpointsMigrations {
  migration_version: number;
}

export interface PlayerpointsPoints {
  id: Generated<number>;
  points: number;
  uuid: string;
}

export interface PlayerpointsUsernameCache {
  username: string;
  uuid: string;
}

export interface DB {
  playerpoints_migrations: PlayerpointsMigrations;
  playerpoints_points: PlayerpointsPoints;
  playerpoints_username_cache: PlayerpointsUsernameCache;
}
