/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Commands {
  commandId: Generated<string | null>;
  id: Generated<number | null>;
}

export interface Favorites {
  action: Generated<string | null>;
  favorite: Generated<number | null>;
  id: Generated<number | null>;
}

export interface Reputation {
  acceptReputation: Generated<number | null>;
  id: Generated<number>;
  reputation: Generated<number | null>;
  uuid: Generated<string | null>;
}

export interface DB {
  commands: Commands;
  favorites: Favorites;
  reputation: Reputation;
}
