/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Advertisement {
  created_at: Generated<string>;
  description: string;
  embedded: string | null;
  id: number | null;
  link: string | null;
  owner: string;
  title: string;
}

export interface Alerts {
  created_at: Generated<string>;
  creator: string;
  description: string | null;
  id: Generated<number | null>;
  title: string;
}

export interface Currencies {
  id: number | null;
  imageUrl: string;
  isAvailable: Generated<number>;
  isPublic: Generated<number>;
  title: string;
  value: string | null;
}

export interface ErrorsLogs {
  created_at: Generated<string>;
  description: string;
  id: number | null;
  initiator: string;
  recipient: string;
  type: string;
}

export interface Events {
  created_at: Generated<string>;
  description: string | null;
  id: number | null;
  imageUrl: string | null;
  origin: string;
  reward: string;
  title: string;
}

export interface EventsPlayers {
  created_at: Generated<string>;
  event_id: number;
  id: number | null;
  nickname: string;
  status: string;
}

export interface IpList {
  id: number | null;
  ip: string;
  name: string;
}

export interface MediaLinks {
  id: number | null;
  link: string;
  value: string;
}

export interface MinecraftFacts {
  fact: string;
  id: number | null;
}

export interface MinecraftItems {
  description: string | null;
  id: number | null;
  image: string;
  title: string;
}

export interface Modpack {
  client: string;
  created_at: Generated<string>;
  downloadLink: string;
  id: number | null;
  imageUrl: string;
  mods: string;
  name: string;
  shaders: string | null;
  version: string;
}

export interface News {
  created_at: Generated<string>;
  description: string;
  id: number | null;
  imageUrl: string;
  media_links: string | null;
  tags: string | null;
  title: string;
}

export interface RulesRuleContent {
  description: string | null;
  id: number | null;
  punishment: string | null;
  rule_list_id: string;
  subtitle: string | null;
  title: string;
}

export interface RulesTerminContent {
  article_desc: string;
  article_title: string;
  id: number | null;
}

export interface VotedUsers {
  created_at: Generated<string>;
  id: number | null;
  nickname: string;
}

export interface DB {
  advertisement: Advertisement;
  alerts: Alerts;
  currencies: Currencies;
  errors_logs: ErrorsLogs;
  events: Events;
  events_players: EventsPlayers;
  ip_list: IpList;
  media_links: MediaLinks;
  minecraft_facts: MinecraftFacts;
  minecraft_items: MinecraftItems;
  modpack: Modpack;
  news: News;
  rules_rule_content: RulesRuleContent;
  rules_termin_content: RulesTerminContent;
  voted_users: VotedUsers;
}
