name: fasberry-external

services:
  traefik:
    image: traefik:v3.3
    command: --providers.docker
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./packages/config-traefik/traefik.yml:/traefik.yml
      - ./packages/config-traefik/certs:/certs
      - ./packages/config-traefik/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9080:9080" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=9080"
    networks:
      - traefik_network

  # consul:
  #   image: consul:1.15.4
  #   container_name: consul
  #   ports:
  #     - "8500:8500" # Web UI
  #     - "8600:8600/udp"
  #   command: "agent -server -client=0.0.0.0 -bootstrap-expect=1 -data-dir=/consul/data"
  #   environment:
  #     - CONSUL_BIND_INTERFACE=eth0
  #   networks:
  #     - vault_network
  #   restart: always
  #   volumes:
  #     - ./data/fasberry-external/consul/data:/consul/data
  #     - ./packages/config-vault/consul.hcl:/consul/config/consul.hcl

  # vault:
  #   image: hashicorp/vault:latest
  #   container_name: vault
  #   ports:
  #     - "8200:8200"
  #   restart: always
  #   depends_on:
  #     - consul
  #   networks:
  #     - vault_network
  #   volumes:
  #     - ./packages/config-vault/vault.hcl:/vault/config/vault.hcl
  #   cap_add:
  #     - IPC_LOCK
  #   entrypoint: [ "vault", "server", "-config=/vault/config/vault.hcl" ]

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   ports:
  #     - "${MINIO_PORT}:${MINIO_PORT}"
  #     - "${MINIO_CLIENT_PORT}:${MINIO_CLIENT_PORT}"
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   volumes:
  #     - ./data/fasberry-external/minio/data:/data
  #   command: server /data --console-address ":${MINIO_CLIENT_PORT}"

  payments_db:
    container_name: payments_db
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PAYMENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PAYMENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PAYMENTS_POSTGRES_DB}
    ports:
      - ${PAYMENTS_POSTGRES_PORT}:5432/tcp
    volumes:
      - ./data/fasberry-external/payments-db/data:/var/lib/postgresql/data

  nats:
    container_name: nats
    image: nats:latest
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "-js"
      - "-sd=2G"
      - "--sd=/nats/jetstream"
      - "-m=8222"
      - "--T"
      - "-VV"
      - "--auth=${NATS_AUTH_TOKEN}"
      - "--addr=0.0.0.0"
    environment:
      - NATS_TOKEN=${NATS_AUTH_TOKEN}
    volumes:
      - ./data/fasberry-external/nats/data:/nats
      - ./data/fasberry-external/nats/jetstream:/nats/jetstream
    networks:
      - traefik_network

networks:
  shared-network:
    external: true
  vault_network:
    driver: bridge
  traefik_network:
    external: true