declare module "bun" {
  interface Env {
    LOGGER_BOT_TOKEN: string
    FASBERRY_BOT_TOKEN: string
    LUCKPERMS_POSTGRES_DB_URL: string
    PAYMENTS_POSTGRES_DB_URL: string
    AUTHORIZATION_POSTGRES_DB_URL: string
    ADMIN_TELEGRAM_USER_ID: string
    SERVER_RCON_PASSWORD: string
    MINECRAFT_SERVER_API_URL: string
    MINECRAFT_SERVER_API_PASSWORD: string
    MINECRAFT_SERVER_API_USERNAME: string
    PAYMENTS_POSTGRES_DB: string
    PAYMENTS_POSTGRES_PASSWORD: string
    PAYMENTS_POSTGRES_USER: string
    PAYMENTS_POSTGRES_PORT: string
    LUCKPERMS_POSTGRES_DB: string
    LUCKPERMS_POSTGRES_PASSWORD: string
    LUCKPERMS_POSTGRES_USER: string
    LUCKPERMS_POSTGRES_PORT: string
    AUTHORIZATION_POSTGRES_DB: string
    AUTHORIZATION_POSTGRES_PASSWORD: string
    AUTHORIZATION_POSTGRES_USER: string
    AUTHORIZATION_POSTGRES_PORT: string
    POSTGRES_USER: string
    POSTGRES_DB: string
    POSTGRES_PORT: number
    POSTGRES_PASSWORD: string
    POSTGRES_TENANT_ID: string
    NATS_AUTH_TOKEN:string

    MYSQL_USER: string,
    MYSQL_PASSWORD: string,
    CMI_MYSQL_PORT: number
    PLAYERPOINTS_MYSQL_PORT: number
  }
}
