export const THREAD_REACTIONS: Record<string, string> = {
  "like": "👍", 
  "love": "❤️",
  "laugh": "😂",
  "sad": "😢",
  "heart": "❤",
  "ghost": "👻",
  "clap": "👏",  
  "fire": "🔥",
  "star": "⭐",  
  "party": "🥳",  
  "thumbs_up": "👍",  
  "wink": "😉",  
  "kiss": "💋",  
  "thinking": "🤔", 
  "trophy": "🏆",  
} as const;