declare module "bun" {
  interface Env {
    FORUM_BACKEND_PORT: number;

    FORUM_DATABASE_URL: string;

    SECRET_TOKEN: string;

    POSTGRES_USER: string;
    POSTGRES_DB: string;
    POSTGRES_PORT: number;
    POSTGRES_PASSWORD: string;
    POSTGRES_TENANT_ID: string;

    PAYMENTS_POSTGRES_DB_URL: string,
    PAYMENTS_POSTGRES_DB: string,
    PAYMENTS_POSTGRES_PASSWORD: string,
    PAYMENTS_POSTGRES_USER: string,
    PAYMENTS_POSTGRES_PORT: string;

    LUCKPERMS_POSTGRES_DB: string;
    LUCKPERMS_POSTGRES_PASSWORD: string;
    LUCKPERMS_POSTGRES_USER: string;
    LUCKPERMS_POSTGRES_PORT: string;

    AUTHORIZATION_POSTGRES_DB: string
    AUTHORIZATION_POSTGRES_PASSWORD: string
    AUTHORIZATION_POSTGRES_USER: string
    AUTHORIZATION_POSTGRES_PORT: string
    
    NATS_AUTH_TOKEN: string

    SUPABASE_SERVICE_ROLE_KEY: string;
    NEXT_PUBLIC_SUPABASE_URL: string
  }
}