declare module "bun" {
  interface Env {
    PAYMENT_BACKEND_PORT: number,

    SECRET_TOKEN: string;

    ARC_PAY_API_URL: string,
    ARC_PAY_API_KEY: string,
    ARC_PAY_PRIVATE_KEY: string

    PAYMENTS_POSTGRES_DB_URL: string,
    PAYMENTS_POSTGRES_DB: string,
    PAYMENTS_POSTGRES_PASSWORD: string,
    PAYMENTS_POSTGRES_USER: string,
    PAYMENTS_POSTGRES_PORT: string;

    CRYPTO_PAY_MAINNET_URL: string;
    CRYPTO_PAY_TESTNET_URL: string;
    CRYPTO_PAY_MAINNET_TOKEN: string;
    CRYPTO_PAY_TESTNET_TOKEN: string;

    LUCKPERMS_POSTGRES_DB: string;
    LUCKPERMS_POSTGRES_PASSWORD: string;
    LUCKPERMS_POSTGRES_USER: string;
    LUCKPERMS_POSTGRES_PORT: string;

    AUTHORIZATION_POSTGRES_DB_URL: string
    AUTHORIZATION_POSTGRES_PASSWORD: string;
    AUTHORIZATION_POSTGRES_PORT: number;
    AUTHORIZATION_POSTGRES_DB: string;
    AUTHORIZATION_POSTGRES_USER: string;

    POSTGRES_USER: string,
    POSTGRES_DB: string,
    POSTGRES_PORT: number,
    POSTGRES_PASSWORD: string
    POSTGRES_TENANT_ID: string,

    NATS_AUTH_TOKEN: string

    NEXT_PUBLIC_SUPABASE_URL: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
  }
}